### ISSUE TITLE
RTTI for the published method "Test1" of class "TMyClass" has 38 extra bytes of unknown data!

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#1]
Error message:

```
RTTI for the published method "Test1" of class "TMyClass" has 38 extra bytes of unknown data!
```

Generated by both below projects when using Delphi 2007:

- TestPublishedMethodParams
- TestMorePubMethodParams

See also the comments at https://hallvards.blogspot.nl/2006/05/hack-10-getting-parameters-of.html

**Comment by hvassbotn** [comment]
Caused by PChar-casts that should be made into PAnsiChar-casts.

**Comment by hvassbotn** [comment]
Fix for this included in pull request (that works in XE6 at least) :)

**Comment by jpluimers** [comment]
Note that pull request #3 didn't fix this.

**Comment by hvassbotn** [comment]
Right. Probably some more RTTI there that we don't read yet. As long as the code and RTTI we do use work, we can probably ignore this for now? 

Will have a second look, though.

**Comment by jpluimers** [comment]
Fixed by https://github.com/jpluimers/HVRTTIUtils/commit/bed06e98909ed6f9f5c6c32179e330e14b7ee8d5

- Delphi 2010 and newer maintain a Tail.ParameterCount which results the IF structure coming down to
   1. an if when there are no parameters (I'm not sure this can even happen)
   2. a for loop involving TailParameterCount counting the size of all parameters (and attributes)
- Delphi 2009 and older lack the Tail.ParameterCount so we have a while loop that counts the bytes used by the parameters and stops as soon as we match or exceed the expected Result.Size
