### ISSUE TITLE
Performance test issues

### ISSUE THREAD

**Issue by hvassbotn** [jpluimers/HVRTTIUtils#10]
`DmtTestsUnit` `TDmtTestCase.TMyDescendent_Create_FasterDynamicLoop_Outperforms_SlowDynamicLoop` does some performance testing.

Issues:

1. `GetTickCount` resolution is low. Mitigated a little by adding `WaitForNewTickCount` before doing each timing
2. The methods called have a non-uniform performance profile. The more times they are called, the slower they get. This is because `AddState` calls `TStringList.Add` that causes the list to grow, and worse, for each iteration the `FState` string variable is updated with
 
```
FState := FStateStrings.CommaText
```
So the last method to be measured (Faster or Slow) will always lose.

Improved it quite significantly now, by only updating `FState` when it is needed:

```
function TDmtTestCase.GetState: string;
begin
  if FStateDirty then
    FState := FStateStrings.CommaText;
  Result := FState;
end;

procedure TDmtTestCase.AddState(const Value: string);
begin
  if not Assigned(FStateStrings) then
  begin
    FStateStrings := TStringList.Create();
  end;
  FStateStrings.Add(Value);
  FStateDirty := True;
//  FState := FStateStrings.CommaText;
end;
```

**Comment by jpluimers** [comment]
I think the below changes with `FSkipAddState` already sufficiently worked around the issue:

https://github.com/jpluimers/HVRTTIUtils/commit/085435202b26f02da7f7cdf62fbf1627a18b9178#diff-1020eda684c0dbfff27b13a04e665536R382

**Comment by hvassbotn** [comment]
Agreed. I reverted my changes there. And closed the issue
