### ISSUE TITLE
Fix failure in TMMinus_PropInfo_PubProp_HasValue

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#11]
Right now in at least Delphi 2007 this fails:

```
TMMinus_PropInfo_PubProp_HasValue: ETestFailure
at  $0049CBB5
expected and actual were: <00000000>
```

The reason is that `TMMinus.ClassInfo` returns `nil`.

It is not that the linker smart-links the code away, as this doesn't help solving it:

```
{ TouchTMMinusInstance }

procedure TouchTMMinusInstance();
var
  MMinus: TMMinus;
begin
  MMinus := TMMinus.Create();
  try
    if (MMinus.DefField <> MMinus.DefProp) and (MMinus.PubField <> MMinus.PubProp) then
      MMinus.DefMethod
    else
      MMinus.PubMethod;
  finally
    MMinus.Free;
  end;

end;

initialization
  TouchTMMinusInstance();
  RegisterTest(TMPlusTests.Suite);
end.
```

**Comment by jpluimers** [comment]
Still not fixed in Delphi 2007:

```
TMMinus_PropInfo_PubProp_HasValue: ETestFailure
at  $0049CBB5
expected and actual were: <00000000>
```

Looking at the fix, I think the `CompilerVersion` comparison is wrong:

```
{$IF CompilerVersion <= 15}
  if TMMinus.ClassInfo <> nil then
{$IFEND CompilerVersion <= 15}
```

According to https://github.com/jpluimers/GExperts/blob/master/Source/Framework/GX_CondDefine.inc#L45 `15` means Delphi 7 and https://github.com/jpluimers/GExperts/blob/master/Source/Framework/GX_CondDefine.inc#L60 indicates `19` means Delphi 2007.

But disabling the check also means DUnit will detect no check was made at all.

So I need to think this through a bit more.

**Comment by hvassbotn** [comment]
Yes, I mixed D7 and D2007 :-P. According to this, D2007 is 18.5?

http://delphi.wikia.com/wiki/CompilerVersion_Constant

**Comment by hvassbotn** [comment]
We should probably just ifdef out the entire test method, so that is does
not appear at all for D2007 and earlier
