### ISSUE TITLE
Delphi 2007 fails `TMethodTableTestCase.TMyDescendent_FindPublishedMethodByAddr_FirstDynamic_HasValue`

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#13]
Delphi 2007 fails `TMethodTableTestCase.TMyDescendent_FindPublishedMethodByAddr_FirstDynamic_HasValue`

Delphi XE8 succeeds here.

Check which Delphi versions fail and find out why.

**Comment by hvassbotn** [comment]
There are differences between compiler versions in what combinations of $M+/- and default or published sections - some versions generate RTTI, some versions do not. So the unit test needs to be different for different versions match the compiler issues / bugs / design changes.

**Comment by jpluimers** [comment]
Fixed by https://github.com/jpluimers/HVRTTIUtils/commit/88f90e5473872826b858bf4e8e5896457494c856 

Thanks @hvassbotn for the idea.
