### ISSUE TITLE
Fix IMyMPInterface_DumpInterface_Output_Matches: EAccessViolation revealed by the fix for #1

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#16]
The fix #1 made a new code path accessible, it exposes an AV in Delphi 2010 (and likely 2009) and newer during `IMyMPInterface_DumpInterface_Output_Matches`: `EAccessViolation
at  $0050BC20`

```
Access violation at address 0050BC20 in module 'HVRTTIUtilsTests.exe'. Read of address 6A624F54
```

**Comment by hvassbotn** [comment]
You need to turn on one of these:
{.$M+}{.$TYPEINFO ON}

Otherwise TypeInfo will return nil, I think.

**Comment by jpluimers** [comment]
Fixed by https://github.com/jpluimers/HVRTTIUtils/commit/4fc8f76d1a9d7984740069e16bf2c482a82be548 and cleaned up by https://github.com/jpluimers/HVRTTIUtils/commit/0398458120e6692cdebe29785fd8972cbb8e4fe0
