### ISSUE TITLE
Find out why unit `WebSnapObjs` is being used

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#2]
Unit `WebSnapObjs` is used in these projects:

```
TestMorePubMethodParams
TestPubFieldTable
TestPublishedMethodParams
```

However, `WebSnapObjs` got removed as of Delphi XE5, so if it is really needed in the examples, a replacement unit needs to be found.

**Comment by hvassbotn** [comment]
It can be removed. Probably included there because I experimented a little at the time. It is one of the few units where {$METHODINFO ON} was used in D2006.
