### ISSUE TITLE
Consider defining PAnsiChar if needed - and use PAnsiChar wherever we need pointer arithmetic

### ISSUE THREAD

**Issue by hvassbotn** [jpluimers/HVRTTIUtils#7]

**Comment by jpluimers** [comment]
For now, I've solved this with a mix of `PSymbolChar` and `PByte`. The latter for incrementing pointers for which the size in bytes is known, the former for strings where a symbol character count is known.

I'm not fully sure from which Delphi version `PByte` is defined; I think it's somewhere around Delphi 5. Similar for `PAnsiChar`

I've defined `PSymbolChar` and others so they are named similarly to `TSymbolName` ([introduced in Delphi XE3](http://docwiki.embarcadero.com/Libraries/XE3/en/System.TypInfo.TSymbolName)).

This should make the meaning of the various pointer operations much clearer.

The change is commit https://github.com/jpluimers/HVRTTIUtils/commit/8b5bf4027b3a8a90b0b07f26c3bf86df940eb21e in the develop branch of file https://github.com/jpluimers/HVRTTIUtils/blob/develop/HVVMT.pas with the code below.

It means you only need the `HVVMT` unit to be able to access these types.

```
type
{$IFDEF UNICODE}
  TSymbolChar = AnsiChar;
  PSymbolChar = PAnsiChar;
{$ELSE}
  TSymbolChar = Char;
  PSymbolChar = PChar;
{$ENDIF UNICODE}
{$IF CompilerVersion <= 23}  // Delphi XE3 or older
  TSymbolNameBase = string[255];
  TSymbolName = type TSymbolNameBase;
{$ELSE}
  TSymbolNameBase = TypInfo.TSymbolNameBase;
  TSymbolName = TypInfo.TSymbolNameBase;
{$IFEND CompilerVersion <= 23}
  PSymbolName = ^TSymbolName;
```

**Comment by hvassbotn** [comment]
PByte has existed a long time but it became magic (with support for pointer arithmetic) only when the $POINTERMATH directive was introduced with Delphi 2009. 

So for D2007 and earlier we must stick to PAnsiChar (or typedefs based on it) - or resort to integer/cardinal/ptrint casts.

**Comment by hvassbotn** [comment]
https://community.embarcadero.com/blogs/entry/taking-a-big-pbyte-of-pointer-math-38852

**Comment by hvassbotn** [comment]
Commited fix
