### ISSUE TITLE
Fix EAssertionFailed with message 'Instance.ClassType TMyDescendent2 <> TMyClass TMyClass 

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#8]
Fix this error from the unit tests:

```
Project HVRTTIUtilsTests.exe raised exception class EAssertionFailed with message 'Instance.ClassType TMyDescendent2 <> TMyClass TMyClass (...\HVRTTIUtils\Tests\DmtTestsUnit.pas, line 212)'.
```

Reproduce by running the tests in any Delphi version >= 2007.

I think this assert is wrong: https://github.com/jpluimers/HVRTTIUtils/blob/develop/Tests/DmtTestsUnit.pas#L212

**Comment by hvassbotn** [comment]
I haven't had time to run this yet. The reason for the assert is that the optimization trick only works if the address of the dynamic method does not change. The assert is a little too strict - it should really check if the address of the dynamic method of this instance is the same as the already pre-computed method address. 

https://github.com/jpluimers/HVRTTIUtils/blob/develop/Tests/DmtTestsUnit.pas#L468

So this line triggers the assert now. If TMyDescendent2 had overridden the FirstDynamic method, the hack would fail. It doesn't so the assert should have been relaxed from a ClassType check to a slightly more complex dynamic method address check.

**Comment by jpluimers** [comment]
Fixed by @hvassbotn  in https://github.com/jpluimers/HVRTTIUtils/commit/3d4f4d2134bb5539efe3e692347cbfed5637a0da
